# Generated by Django 4.2.24 on 2025-09-24 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('icon', models.CharField(default='fa-regular fa-pen-to-square', max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
        ),
    ]
